/**
 * Day 17 - Example 3: Omit<T, K> Utility Type
 *
 * Demonstrates how Omit excludes specific properties from a type
 * Use case: Removing sensitive data, creating input types, safe logging
 */

// ============================================
// Example 1: Basic Omit Usage
// ============================================

interface User {
  id: string;
  username: string;
  email: string;
  password: string;
  age: number;
  createdAt: Date;
}

// Public profile - exclude sensitive data
type PublicUser = Omit<User, 'password'>;

// User list view - exclude password and detailed timestamps
type UserListItem = Omit<User, 'password' | 'createdAt'>;

// Safe for logging - exclude password
type SafeUser = Omit<User, 'password'>;

function displayPublicProfile(user: PublicUser): void {
  console.log('Public Profile:', {
    id: user.id,
    username: user.username,
    email: user.email,
    age: user.age
  });
  // Can't access user.password - TypeScript error
}

function logUserAction(user: SafeUser, action: string): void {
  console.log(`[LOG] ${user.username} performed: ${action}`);
  // Safe to log - no password in type
}

const fullUser: User = {
  id: '1',
  username: 'john_doe',
  email: 'john@example.com',
  password: 'hashed_password_123',
  age: 30,
  createdAt: new Date()
};

// Create safe version for public display
const publicUser: PublicUser = {
  id: fullUser.id,
  username: fullUser.username,
  email: fullUser.email,
  age: fullUser.age,
  createdAt: fullUser.createdAt
};

displayPublicProfile(publicUser);

console.log('✅ Example 1: Basic Omit completed\n');


// ============================================
// Example 2: Safe Configuration Logging
// ============================================

interface SDKConfig {
  accessToken: string;        // 🔒 Sensitive
  phoneNumberId: string;
  apiVersion: string;
  timeout: number;
  retryAttempts: number;
  baseURL: string;
  webhookSecret?: string;     // 🔒 Sensitive
  debug: boolean;
}

// Safe config excludes all secrets
type SafeConfig = Omit<SDKConfig, 'accessToken' | 'webhookSecret'>;

class WhatsAppClient {
  private config: SDKConfig;

  constructor(config: SDKConfig) {
    this.config = config;
    this.logInitialization();
  }

  // Log initialization without exposing secrets
  private logInitialization(): void {
    const safeConfig: SafeConfig = {
      phoneNumberId: this.config.phoneNumberId,
      apiVersion: this.config.apiVersion,
      timeout: this.config.timeout,
      retryAttempts: this.config.retryAttempts,
      baseURL: this.config.baseURL,
      debug: this.config.debug
    };

    console.log('✅ WhatsApp SDK initialized with config:', safeConfig);
    // No secrets in logs!
  }

  // Public method to get safe config
  getConfig(): SafeConfig {
    const { accessToken, webhookSecret, ...safeConfig } = this.config;
    return safeConfig;
  }
}

const client = new WhatsAppClient({
  accessToken: 'EAAxxxxxxxxxxxxxxx',  // Secret
  phoneNumberId: '123456789',
  apiVersion: 'v17.0',
  timeout: 5000,
  retryAttempts: 3,
  baseURL: 'https://graph.facebook.com',
  webhookSecret: 'webhook_secret_xxx',  // Secret
  debug: true
});

console.log('Public config:', client.getConfig());

console.log('✅ Example 2: Safe Configuration Logging completed\n');


// ============================================
// Example 3: Create vs Update Input Types
// ============================================

interface BlogPost {
  id: string;              // Generated by database
  title: string;
  slug: string;            // Generated from title
  content: string;
  authorId: string;
  published: boolean;
  viewCount: number;       // Managed by system
  createdAt: Date;         // Generated by system
  updatedAt: Date;         // Generated by system
  publishedAt?: Date;      // Generated when published
}

// Create input - user doesn't provide system-generated fields
type CreateBlogPostInput = Omit<
  BlogPost,
  'id' | 'slug' | 'viewCount' | 'createdAt' | 'updatedAt' | 'publishedAt'
>;

// Update input - user can't change id, author, or timestamps
type UpdateBlogPostInput = Omit<
  BlogPost,
  'id' | 'authorId' | 'slug' | 'viewCount' | 'createdAt' | 'updatedAt' | 'publishedAt'
>;

class BlogPostService {
  private posts: Map<string, BlogPost> = new Map();
  private idCounter = 1;

  create(input: CreateBlogPostInput): BlogPost {
    const post: BlogPost = {
      ...input,
      id: `post-${this.idCounter++}`,
      slug: this.generateSlug(input.title),
      viewCount: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
      publishedAt: input.published ? new Date() : undefined
    };

    this.posts.set(post.id, post);
    console.log(`Post created: ${post.title}`);
    return post;
  }

  update(id: string, input: UpdateBlogPostInput): BlogPost | undefined {
    const existing = this.posts.get(id);

    if (!existing) {
      console.log(`Post ${id} not found`);
      return undefined;
    }

    const updated: BlogPost = {
      ...existing,
      ...input,
      updatedAt: new Date(),
      publishedAt: input.published && !existing.published ? new Date() : existing.publishedAt
    };

    this.posts.set(id, updated);
    console.log(`Post updated: ${id}`);
    return updated;
  }

  private generateSlug(title: string): string {
    return title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  }
}

const blogService = new BlogPostService();

// Create post - only provide user-controlled fields
const newPost = blogService.create({
  title: 'Getting Started with TypeScript',
  content: 'TypeScript is a typed superset of JavaScript...',
  authorId: 'user-123',
  published: false
});

console.log('New post:', newPost);

// Update post - can't change id, author, or timestamps
if (newPost) {
  blogService.update(newPost.id, {
    title: 'Getting Started with TypeScript - Updated',
    content: 'Updated content...',
    published: true
  });
}

console.log('✅ Example 3: Create vs Update Types completed\n');


// ============================================
// Example 4: API Request vs Response Types
// ============================================

interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  categoryId: string;
  vendorId: string;
  sku: string;
  weight: number;
  images: string[];
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
  updatedBy: string;
}

// POST /products - User doesn't send system-generated fields
type CreateProductRequest = Omit<
  Product,
  'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'
>;

// PATCH /products/:id - User can update some fields
type UpdateProductRequest = Partial<
  Omit<Product, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy' | 'vendorId'>
>;

// GET /products - Response includes everything
type ProductResponse = Product;

// GET /products (list) - Response excludes some heavy fields
type ProductListResponse = Omit<Product, 'description' | 'createdBy' | 'updatedBy'>;

class ProductAPI {
  private products: Map<string, Product> = new Map();

  // POST /products
  createProduct(userId: string, request: CreateProductRequest): ProductResponse {
    const product: Product = {
      ...request,
      id: `prod-${Date.now()}`,
      createdAt: new Date(),
      updatedAt: new Date(),
      createdBy: userId,
      updatedBy: userId
    };

    this.products.set(product.id, product);
    console.log(`Product created: ${product.name}`);
    return product;
  }

  // PATCH /products/:id
  updateProduct(
    id: string,
    userId: string,
    request: UpdateProductRequest
  ): ProductResponse | undefined {
    const existing = this.products.get(id);

    if (!existing) {
      return undefined;
    }

    const updated: Product = {
      ...existing,
      ...request,
      updatedAt: new Date(),
      updatedBy: userId
    };

    this.products.set(id, updated);
    console.log(`Product updated: ${id}`);
    return updated;
  }

  // GET /products/:id
  getProduct(id: string): ProductResponse | undefined {
    return this.products.get(id);
  }

  // GET /products (list)
  listProducts(): ProductListResponse[] {
    return Array.from(this.products.values()).map(product => {
      const { description, createdBy, updatedBy, ...listItem } = product;
      return listItem;
    });
  }
}

const productAPI = new ProductAPI();

// Create product
const product = productAPI.createProduct('admin-1', {
  name: 'Wireless Keyboard',
  description: 'Mechanical wireless keyboard with RGB',
  price: 89.99,
  stock: 50,
  categoryId: 'cat-1',
  vendorId: 'vendor-1',
  sku: 'WK-001',
  weight: 1.2,
  images: ['image1.jpg', 'image2.jpg']
});

// Update product
productAPI.updateProduct(product.id, 'admin-1', {
  price: 79.99,
  stock: 45
});

// List products (lightweight)
const productList = productAPI.listProducts();
console.log('Product list:', productList);

console.log('✅ Example 4: API Request/Response Types completed\n');


// ============================================
// Example 5: Database Models vs DTOs
// ============================================

interface UserEntity {
  // Database fields
  id: string;
  email: string;
  passwordHash: string;
  salt: string;
  emailVerified: boolean;
  verificationToken?: string;

  // User data
  firstName: string;
  lastName: string;
  phoneNumber?: string;

  // Metadata
  createdAt: Date;
  updatedAt: Date;
  lastLoginAt?: Date;
  loginCount: number;

  // Internal
  deletedAt?: Date;
  deletedBy?: string;
}

// DTO for registration - exclude internal fields
type RegisterUserDTO = Omit<
  UserEntity,
  'id' | 'passwordHash' | 'salt' | 'emailVerified' | 'verificationToken' |
  'createdAt' | 'updatedAt' | 'lastLoginAt' | 'loginCount' | 'deletedAt' | 'deletedBy'
> & {
  password: string;  // Plain password in DTO, hashed in entity
};

// DTO for user profile - exclude sensitive and internal fields
type UserProfileDTO = Omit<
  UserEntity,
  'passwordHash' | 'salt' | 'verificationToken' | 'deletedAt' | 'deletedBy'
>;

// DTO for public display
type PublicUserDTO = Omit<
  UserEntity,
  'email' | 'passwordHash' | 'salt' | 'emailVerified' | 'verificationToken' |
  'phoneNumber' | 'lastLoginAt' | 'loginCount' | 'deletedAt' | 'deletedBy'
>;

class UserRepository {
  private users: Map<string, UserEntity> = new Map();

  register(dto: RegisterUserDTO): PublicUserDTO {
    const { password, ...userData } = dto;

    const entity: UserEntity = {
      ...userData,
      id: `user-${Date.now()}`,
      passwordHash: this.hashPassword(password),
      salt: this.generateSalt(),
      emailVerified: false,
      verificationToken: this.generateToken(),
      createdAt: new Date(),
      updatedAt: new Date(),
      loginCount: 0
    };

    this.users.set(entity.id, entity);
    console.log(`User registered: ${entity.email}`);

    // Return public DTO
    return {
      id: entity.id,
      firstName: entity.firstName,
      lastName: entity.lastName,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt
    };
  }

  getProfile(id: string): UserProfileDTO | undefined {
    const entity = this.users.get(id);
    if (!entity) return undefined;

    // Exclude sensitive fields
    const { passwordHash, salt, verificationToken, deletedAt, deletedBy, ...profile } = entity;
    return profile;
  }

  getPublicProfile(id: string): PublicUserDTO | undefined {
    const entity = this.users.get(id);
    if (!entity) return undefined;

    // Only public fields
    return {
      id: entity.id,
      firstName: entity.firstName,
      lastName: entity.lastName,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt
    };
  }

  private hashPassword(password: string): string {
    return `hashed_${password}`;
  }

  private generateSalt(): string {
    return 'salt_' + Math.random();
  }

  private generateToken(): string {
    return 'token_' + Math.random();
  }
}

const userRepo = new UserRepository();

// Register new user
const registeredUser = userRepo.register({
  email: 'john@example.com',
  firstName: 'John',
  lastName: 'Doe',
  phoneNumber: '+1234567890',
  password: 'secure_password'
});

console.log('Registered user (public):', registeredUser);

// Get user profile (includes email, but not password)
const profile = userRepo.getProfile(registeredUser.id);
console.log('User profile:', profile);

// Get public profile (minimal data)
const publicProfile = userRepo.getPublicProfile(registeredUser.id);
console.log('Public profile:', publicProfile);

console.log('✅ Example 5: Database Models vs DTOs completed\n');


// ============================================
// Example 6: Combining Omit with Other Utilities
// ============================================

interface Employee {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  department: string;
  role: string;
  salary: number;
  ssn: string;
  startDate: Date;
  endDate?: Date;
  isActive: boolean;
}

// Omit sensitive, then make optional for updates
type UpdateEmployeeInput = Partial<Omit<Employee, 'id' | 'password' | 'salary' | 'ssn'>>;

// Omit sensitive, then pick only specific fields
type EmployeeCard = Pick<Omit<Employee, 'password' | 'salary' | 'ssn'>, 'id' | 'firstName' | 'lastName' | 'role'>;

// Omit internal fields for public API
type PublicEmployee = Omit<Employee, 'password' | 'salary' | 'ssn' | 'endDate'>;

function updateEmployee(id: string, updates: UpdateEmployeeInput): void {
  console.log(`Updating employee ${id}:`, updates);
  // Can update some fields, but not id, password, salary, ssn
}

function displayEmployeeCard(employee: EmployeeCard): void {
  console.log(`${employee.firstName} ${employee.lastName} - ${employee.role}`);
}

// Demonstrate usage
updateEmployee('emp-1', {
  department: 'Engineering',
  role: 'Senior Developer'
});

const employeeCard: EmployeeCard = {
  id: 'emp-1',
  firstName: 'John',
  lastName: 'Doe',
  role: 'Senior Developer'
};

displayEmployeeCard(employeeCard);

console.log('✅ Example 6: Combining Omit with Other Utilities completed\n');


// ============================================
// Summary
// ============================================

console.log(`
📚 Omit<T, K> Summary:
-------------------
✓ Excludes specific properties from a type
✓ Perfect for removing sensitive data
✓ Creates safe versions for logging/display
✓ Useful for input types (omit generated fields)
✓ Type-safe property exclusion

Common use cases:
- Removing sensitive data (passwords, tokens)
- Creating input types (omit DB-generated fields)
- Safe logging and debugging
- Public API responses
- DTOs from database entities

Omit vs Pick:
- Use Omit when excluding FEW from MANY
- Use Pick when selecting FEW from MANY
- Pick what you WANT vs Omit what you DON'T WANT

How Omit works:
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>
- Gets all keys of T
- Excludes K from those keys
- Picks remaining keys
`);
